#ifndef STUB_Programs_H__
#define STUB_Programs_H__

#include "../courier/Programs.h"

namespace Courier {
    namespace Stub {
        namespace Programs {
            QList<Courier::Programs::Info> infoList = {
                 {14, "Authentication",  2,  1, "GetStrongCredentials"},
                 {14, "Authentication",  2,  2, "CheckSimpleCredentials"},
                 {14, "Authentication",  2,  3, "CreateStrongKey"},
                 {14, "Authentication",  2,  4, "ChangeStrongKey"},
                 {14, "Authentication",  2,  5, "DeleteStrongKey"},
                 {14, "Authentication",  2,  6, "CreateSimpleKey"},
                 {14, "Authentication",  2,  7, "ChangeSimpleKey"},
                 {14, "Authentication",  2,  8, "DeleteSimpleKey"},
                 {14, "Authentication",  3,  1, "GetStrongCredentials"},
                 {14, "Authentication",  3,  2, "CheckSimpleCredentials"},
                 {14, "Authentication",  3,  3, "CreateStrongKey"},
                 {14, "Authentication",  3,  4, "ChangeStrongKey"},
                 {14, "Authentication",  3,  5, "DeleteStrongKey"},
                 {14, "Authentication",  3,  6, "CreateSimpleKey"},
                 {14, "Authentication",  3,  7, "ChangeSimpleKey"},
                 {14, "Authentication",  3,  8, "DeleteSimpleKey"},
                 {14, "Authentication",  3,  9, "TradeProxyForCredentials"},
                 { 0, "BulkData",  1,  0, "Send"},
                 { 0, "BulkData",  1,  1, "Receive"},
                 { 0, "BulkData",  1,  2, "Cancel"},
                 { 2, "Clearinghouse",  2,  0, "RetrieveAddresses"},
                 { 2, "Clearinghouse",  2,  1, "ListDomainServed"},
                 { 2, "Clearinghouse",  2,  2, "CreateObject"},
                 { 2, "Clearinghouse",  2,  3, "DeleteObject"},
                 { 2, "Clearinghouse",  2,  4, "LookupObject"},
                 { 2, "Clearinghouse",  2,  5, "ListOrganizations"},
                 { 2, "Clearinghouse",  2,  6, "ListDomain"},
                 { 2, "Clearinghouse",  2,  7, "ListObjects"},
                 { 2, "Clearinghouse",  2,  8, "ListAliases"},
                 { 2, "Clearinghouse",  2,  9, "ListAliasesOf"},
                 { 2, "Clearinghouse",  2, 10, "CreateAlias"},
                 { 2, "Clearinghouse",  2, 11, "DeleteAlias"},
                 { 2, "Clearinghouse",  2, 12, "AddGroupProperty"},
                 { 2, "Clearinghouse",  2, 13, "AddItemProperty"},
                 { 2, "Clearinghouse",  2, 14, "DeleteProperty"},
                 { 2, "Clearinghouse",  2, 15, "ListProperties"},
                 { 2, "Clearinghouse",  2, 16, "RetrieveItem"},
                 { 2, "Clearinghouse",  2, 17, "ChangeItem"},
                 { 2, "Clearinghouse",  2, 18, "RetrieveMembers"},
                 { 2, "Clearinghouse",  2, 19, "AddMember"},
                 { 2, "Clearinghouse",  2, 20, "AddSelf"},
                 { 2, "Clearinghouse",  2, 21, "DeleteMember"},
                 { 2, "Clearinghouse",  2, 22, "DeleteSelf"},
                 { 2, "Clearinghouse",  2, 23, "IsMember"},
                 { 2, "Clearinghouse",  3,  0, "RetrieveAddresses"},
                 { 2, "Clearinghouse",  3,  1, "ListDomainServed"},
                 { 2, "Clearinghouse",  3,  2, "CreateObject"},
                 { 2, "Clearinghouse",  3,  3, "DeleteObject"},
                 { 2, "Clearinghouse",  3,  4, "LookupObject"},
                 { 2, "Clearinghouse",  3,  5, "ListOrganizations"},
                 { 2, "Clearinghouse",  3,  6, "ListDomain"},
                 { 2, "Clearinghouse",  3,  7, "ListObjects"},
                 { 2, "Clearinghouse",  3,  8, "ListAliases"},
                 { 2, "Clearinghouse",  3,  9, "ListAliasesOf"},
                 { 2, "Clearinghouse",  3, 10, "CreateAlias"},
                 { 2, "Clearinghouse",  3, 11, "DeleteAlias"},
                 { 2, "Clearinghouse",  3, 12, "AddGroupProperty"},
                 { 2, "Clearinghouse",  3, 13, "AddItemProperty"},
                 { 2, "Clearinghouse",  3, 14, "DeleteProperty"},
                 { 2, "Clearinghouse",  3, 15, "ListProperties"},
                 { 2, "Clearinghouse",  3, 16, "RetrieveItem"},
                 { 2, "Clearinghouse",  3, 17, "ChangeItem"},
                 { 2, "Clearinghouse",  3, 18, "RetrieveMembers"},
                 { 2, "Clearinghouse",  3, 19, "AddMember"},
                 { 2, "Clearinghouse",  3, 20, "AddSelf"},
                 { 2, "Clearinghouse",  3, 21, "DeleteMember"},
                 { 2, "Clearinghouse",  3, 22, "DeleteSelf"},
                 { 2, "Clearinghouse",  3, 23, "IsMember"},
            };
        }
    }
}
#endif
